# NOTE: Based on https://github.com/fedarko/qeeseburger/blob/master/.travis.yml
language: python
python:
    - "3.6"
    - "3.7"
install:
    - pip install numpy networkx pytest pytest-cov flake8 black
script:
    - make test
    - make stylecheck
after_success:
    - wget -O codecov.sh https://codecov.io/bash
    # Upload coverage information
    - bash codecov.sh -c
